# Generated by Django 3.0.4 on 2020-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200320_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_calendar',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_calendar',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grades',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Course'),
        ),
    ]
