# Generated by Django 3.0.4 on 2020-03-24 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200322_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'شهر'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'دوره'},
        ),
        migrations.AlterModelOptions(
            name='course_calendar',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': 'پایه'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name_plural': 'درس'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': 'نقش'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'کاربر'},
        ),
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Lesson', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='course_calendar',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Course', verbose_name='دوره'),
        ),
        migrations.AlterField(
            model_name='course_calendar',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='course_calendar',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='code',
            field=models.CharField(max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='code',
            field=models.CharField(max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Grade', verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Lesson', verbose_name='درس پدر'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=10, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=30, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.City', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grades',
            field=models.ManyToManyField(blank=True, to='accounts.Grade', verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='رمز'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payments',
            field=models.ManyToManyField(blank=True, to='accounts.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='تل�?ن همراه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Role', verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='نام کاربری'),
        ),
    ]
