# Generated by Django 3.0.4 on 2020-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200324_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_calendar',
            options={'ordering': ['start_date'], 'verbose_name_plural': 'زمان برگزاری'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='تلفن همراه'),
        ),
    ]
