# Generated by Django 3.0.4 on 2020-03-30 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['start_date'], 'verbose_name': 'دوره', 'verbose_name_plural': 'دوره'},
        ),
        migrations.AlterModelOptions(
            name='course_calendar',
            options={'ordering': ['start_date'], 'verbose_name': 'زمان برگزاری', 'verbose_name_plural': 'زمان برگزاری'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['code'], 'verbose_name': 'پایه', 'verbose_name_plural': 'پایه'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'درس', 'verbose_name_plural': 'درس'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'نقش', 'verbose_name_plural': 'نقش'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='defaults/course.jpg', upload_to='courses_image/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_calendar',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_calendar',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
            preserve_default=False,
        ),
    ]
