# Generated by Django 3.0.4 on 2020-04-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200330_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_calendar',
            options={'ordering': ['end_date'], 'verbose_name': 'زمان برگزاری', 'verbose_name_plural': 'زمان برگزاری'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='grade',
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Grade', verbose_name='پایه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='تلفن همراه'),
        ),
    ]
