# Generated by Django 3.0.4 on 2020-04-15 19:17

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200406_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_document', models.FileField(blank=True, null=True, upload_to=accounts.models.document_directory_path, verbose_name='فایل')),
                ('upload_date', models.DateTimeField(verbose_name='تاریخ بارگذاری')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Course', verbose_name='دوره')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Lesson', verbose_name='درس')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='فرد بارگذار')),
            ],
            options={
                'verbose_name': 'فایل ها',
                'verbose_name_plural': 'فایل ها',
                'ordering': ['-upload_date'],
            },
        ),
    ]
